sonar.projectKey=SIVAD
sonar.projectName=SIVAD
sonar.host.url=http://localhost:9000
sonar.token=sqp_a87dea2ec0f359ee2aca3eca86f9cf97eb468af3
sonar.sources=app
sonar.language=py
sonar.exclusions=venv/**,**/__pycache__/**,**/*.pyc
sonar.python.version=3
